import { z } from "zod";
import { isNoiseTag } from "./lib/tag-parser.js";

export const TagCategorySchema = z.object({
  prefix: z.string(),
  description: z.string().optional(),
  tags: z.array(z.string()),
});

export const TagMappingSchema = z.object({
  from: z.array(z.string()),
  to: z.string().nullable(),
});

export const TagSchemeSchema = z.object({
  categories: z.array(TagCategorySchema),
  mappings: z.array(TagMappingSchema),
  removals: z.array(z.string()),
});

export type TagCategory = z.infer<typeof TagCategorySchema>;
export type TagMapping = z.infer<typeof TagMappingSchema>;
export type TagScheme = z.infer<typeof TagSchemeSchema>;

export function parseTagScheme(raw: unknown): TagScheme {
  return TagSchemeSchema.parse(raw);
}

export const NOISE_TAG_PATTERNS = {
  exact: ["heading"],
  prefixes: ["follow-up-required-"],
  containsChars: ["="],
};

export const SCHEME_NOTE_PATH = "Proposed Tagging System.md";

/**
 * Universal tag mappings that work for any vault.
 * These are noise patterns and widely-agreed conventions.
 * Vault-specific mappings come from plan-mappings.json (generated by plan phase).
 */
export const TAG_MAPPINGS: Record<string, string | null> = {
  // === NOISE / REMOVAL (universal) ===
  "heading": null,           // Google Docs anchors
  "follow-up-required-weekly": null,
  "follow-up-required-monthly": null,
  "follow-up-required-quarterly": null,
};

export interface AuditMappings {
  mappings: Record<string, string | null>;
}

/**
 * Look up a tag in the mapping table.
 * Priority: noise patterns → exact match in mappings → normalized match → hardcoded → valid format check → unmapped.
 *
 * Note: We check the ORIGINAL tag (lowercase only) in mappings before normalizing underscores.
 * This ensures that ai_tools→ai-tools is returned as "map" (format change) rather than
 * being normalized first and finding ai-tools→ai-tools (identity/keep).
 */
export function lookupTagMapping(
  tag: string,
  loadedMappings?: AuditMappings,
): { action: "map" | "remove" | "keep" | "unmapped"; newTag: string | null } {
  const lowercased = tag.toLowerCase();
  const normalized = lowercased.replace(/_/g, "-");

  // Check noise patterns first (using normalized form)
  if (isNoiseTag(normalized)) {
    return { action: "remove", newTag: null };
  }

  // Check loaded mappings: try ORIGINAL (lowercase) first, then normalized
  // This ensures format-fix mappings like ai_tools→ai-tools are found
  if (loadedMappings) {
    // First: try exact match with lowercase original
    if (lowercased in loadedMappings.mappings) {
      const newTag = loadedMappings.mappings[lowercased];
      if (newTag === null) return { action: "remove", newTag: null };
      if (newTag === lowercased) return { action: "keep", newTag };
      return { action: "map", newTag };
    }
    // Second: try normalized form (underscores→hyphens)
    if (normalized in loadedMappings.mappings) {
      const newTag = loadedMappings.mappings[normalized];
      if (newTag === null) return { action: "remove", newTag: null };
      if (newTag === normalized) return { action: "keep", newTag };
      return { action: "map", newTag };
    }
  }

  // Check hardcoded universal mappings (noise patterns only)
  if (normalized in TAG_MAPPINGS) {
    const newTag = TAG_MAPPINGS[normalized];
    if (newTag === null) return { action: "remove", newTag: null };
    if (newTag === normalized) return { action: "keep", newTag };
    return { action: "map", newTag };
  }

  // Check if it's already a valid hierarchical tag
  const VALID_PREFIXES = ["status/", "type/", "area/", "project/", "skill/", "tool/", "topic/"];
  if (VALID_PREFIXES.some((p) => normalized.startsWith(p))) {
    return { action: "keep", newTag: normalized };
  }

  // Check if it's a valid flat kebab-case topic tag
  if (/^[a-z0-9]+(-[a-z0-9]+)*$/.test(normalized)) {
    return { action: "keep", newTag: normalized };
  }

  return { action: "unmapped", newTag: null };
}
